# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=prices.models.default_slug, unique=True)),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=prices.models.default_slug, unique=True)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=prices.models.default_slug, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=prices.models.default_slug, unique=True),
        ),
        migrations.AddField(
            model_name='good',
            name='cath',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.Category'),
        ),
        migrations.AddField(
            model_name='good',
            name='langs',
            field=models.ManyToManyField(to='prices.Lang'),
        ),
        migrations.AddField(
            model_name='good',
            name='tags',
            field=models.ManyToManyField(to='prices.Tag'),
        ),
        migrations.AddField(
            model_name='good',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.Unit'),
        ),
    ]
