# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_info', '0002_auto_20170228_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
