# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_info', '0005_auto_20170304_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('image', models.ImageField(upload_to='static/images/os')),
            ],
        ),
    ]
