# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_info', '0007_device_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='os',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
