# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-05 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_info', '0009_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='alt_image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
